[package]
name = "lumora"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lumorac"
path = "src/lumorac.rs"

[dependencies]
pest = "2.8"
pest_derive = "2.8"
wasm-encoder = "0.229"
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
wasmtime = "32.0"
